---
- name: Create sway config directory
  become: true
  ansible.builtin.file:
    path: "{{ user.home }}/.config/sway"
    state: directory
    mode: '0750'
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
  loop: "{{ swaywm_users|flatten(levels=1) }}"
  loop_control:
    loop_var: user

- name: Deploy sway config file
  become: true
  ansible.builtin.template:
    src: "templates/config.j2"
    dest: "{{ user.home }}/.config/sway/config"
    mode: "0640"
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    backup: true
  loop: "{{ swaywm_users|flatten(levels=1) }}"
  loop_control:
    loop_var: user
